### ISSUE TITLE
loading multiple modules in loadPackage

### ISSUE THREAD

**Issue by jefferyshivers** [openlilylib/oll-core#13]
Is this really the best/expected way to load modules within `\loadPackage`, or am I missing a cleaner-looking syntax? :

```lilypond
\loadPackage \with {
  modules = #(list '(annotate) '(editorial-functions))
} scholarly

%% alternatively

\loadPackage \with {
  modules = #'((annotate) (editorial-functions))
} scholarly
```

Nevermind that the above doesn't actually *reload* editorial-functions.

**Comment by uliska** [comment]
I'll have to look into that, but it doesn't look good. If that's really how it is implemented we should change it so you can use

```lilypond
\loadPackage \with {
  modules = #'(annotate editorial-functions)
} scholarly

%% alternatively

\loadPackage \with {
  modules = annotate.editorial-functions
} scholarly
```

This may well warrant improvement because when I wrote that code I wasn't even close to being as confident with Scheme as I'm today ...

I'm not sure how to understand your last sentence: what *does* the code currently do? The *intention* was certainly to load modules only once, i.e. detect if a called module has already been loaded.

**Comment by jefferyshivers** [comment]
> I'm not sure how to understand your last sentence: what does the code currently do? The intention was certainly to load modules only once, i.e. detect if a called module has already been loaded.

I was merely clarifying that I realize there is no need to actually load *annotate* and *editorial-editions* since the former implicitly loads the latter. It's simply the only use case (and thus the only way to even test loadPackage with multiple modules) since no other packages have multiple modules (right?).

**Comment by jefferyshivers** [comment]
```lilypond
\loadPackage \with {
  modules = #'(annotate editorial-functions)
} scholarly
```
Yes, glancing at the code it seems like that would actually work. Hm.

**Comment by uliska** [comment]
Oh no, I just tested the different invocations. The symbol list `modules = annotate.editorial-functions` tries to load the module `scholarly->annotate->editorial-functions` which is of course not registered.

I think this needs reconsideration. We should clarify if there may ever arise the wish for submodules like that (not unlikely) and find a better syntax for calling multiple modules at once.

**Comment by uliska** [comment]
> no other packages have multiple modules (right?).

Yet.

**Comment by uliska** [comment]
For the record. In the `config` branch I'm currently rewriting the package/module handling code, and I'll look into this issue.

I realized that we *do* need a way to have nested modules because we don't only have packages like scholarLY with `scholarly.annotate` or the new anaLYsis with `analysis.arrows` but also the snippets repository. Although I initially thought this should completely "resolve" in new "proper" package I realize now that we should of course keep it as a stack of useful but loosely categorized functions. But it should be integrated in the oll-core infrastructure so it's possible to write

```lilypond
\include "oll-core/package.ily"
\loadPackage snippets
\loadModule snippets.notation-snippets.shaping-bezier-curves
```

So what I want to have as interface is the following possibilities:

```lilypond
% A
\loadModule snippets.notation-snippets.shaping-bezier-curves
\loadModule scholarly.annotate

% B
\loadModules analysis arrows.frames

% C
\loadModules snippets #'((notation-snippets shaping-bezier-curves)
                         (editorial-tools auto-transpose))

% D
\loadModules snippets notation-snippets
```

**A** will use the first element as the package and the remainder as the path to the module.

**B** to **D** will use the first argument as package and the remainder to specify modules

**B** loads a number of top-level modules

**C** loads a number of submodules, each specified as a symbol-list?

**D** loads all submodules found below `notation-snippets` (this could get an optional boolean argument to make it recursive or not)

I'll have to think about what that means for the `\loadPackage \with {}` construct.

Any opinions or comments @jefferyshivers ?

**Comment by uliska** [comment]
I'm right now considering this, and I think we will have to live with the two limitations that

* with `\loadModules` we can't provide module options
* with `\loadPackage \with { modules = ... }` we can't provide module options either, but also no submodules

**Comment by uliska** [comment]
And `\loadModule` can now implicitly load the package if that hasn't been loaded yet, so

```lilypond
\include "oll-core/package.ily"
\loadModule scholarly.annotate
```
will properly load the `scholarly` *package* before loading the module

**Comment by uliska** [comment]
OK, I think this has been implemented in the `config` branch.
@jefferyshivers feel free to reopen the issue if there are still things missing (or wrong).
